# Get all books
GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json

###
# Create a book
POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
    "title": "The Power of Now"
}

###
# Update a book
PUT http://localhost:3001/books/be08 HTTP/1.1
Content-Type: application/json

{
    "title":"The Power of Now!!"
}

###
# Delete a book
DELETE http://localhost:3001/books/be08 HTTP/1.1
Content-Type: application/json